import {
  Home,
  Box,
  DollarSign,
  Tag,
  Clipboard,
  Camera,
  AlignLeft,
  UserPlus,
  Users,
  Chrome,
  BarChart,
  Settings,
  Archive,
  LogIn,
  Image,
} from "react-feather";

export const MENUITEMS = [
  {
    id: 10000,
    path: "/dashboard",
    title: "Dashboard",
    icon: Home,
    type: "link",
    badgeType: "primary",
    active: false,
    privilege: true,
    name: "Dashboard Visibility",
  },
  {
    id: 10001,
    path: "/banner",
    title: "Banner",
    icon: Image,
    type: "link",
    badgeType: "primary",
    active: false,
    privilege: true,
    name: "Banner management",
  },
  // {
  //   title: "Products",
  //   icon: Box,
  //   type: "sub",
  //   active: false,
  //   children: [
  //     {
  //       title: "Physical",
  //       type: "sub",
  //       active: false,
  //       children: [
  //         {
  //           path: "/products/physical/category",
  //           title: "Category",
  //           type: "link",
  //         },
  //         {
  //           path: "/products/physical/sub-category",
  //           title: "Sub Category",
  //           type: "link",
  //         },
  //         {
  //           path: "/products/physical/product-list",
  //           title: "Product List",
  //           type: "link",
  //         },
  //         {
  //           path: "/products/physical/product-detail",
  //           title: "Product Detail",
  //           type: "link",
  //         },
  //         {
  //           path: "/products/physical/add-product",
  //           title: "Add Product",
  //           type: "link",
  //         },
  //       ],
  //     },
  //     {
  //       title: "digital",
  //       type: "sub",
  //       active: false,
  //       children: [
  //         {
  //           path: "/products/digital/digital-category",
  //           title: "Category",
  //           type: "link",
  //         },
  //         {
  //           path: "/products/digital/digital-sub-category",
  //           title: "Sub Category",
  //           type: "link",
  //         },
  //         {
  //           path: "/products/digital/digital-product-list",
  //           title: "Product List",
  //           type: "link",
  //         },
  //         {
  //           path: "/products/digital/digital-add-product",
  //           title: "Add Product",
  //           type: "link",
  //         },
  //       ],
  //     },
  //   ],
  // },
  {
    id: 10002,
    title: "Products",
    icon: Box,
    type: "sub",
    active: false,
    privilege: true,
    name: "product managemenet",
    children: [
      {
        path: "/products/physical/category",
        title: "Category",
        type: "link",
      },
      {
        path: "/products/physical/sub-category",
        title: "Sub Category",
        type: "link",
      },
      {
        path: "/products/add",
        title: "Add Product",
        type: "link",
      },
      {
        path: "/products/physical/product-list",
        title: "Product",
        type: "link",
      },
      {
        path: "/product/inventory",
        title: "Inventory Management",
        type: "link",
      },
    ],
  },
  {
    id: 10003,
    title: "Sales",
    privilege: true,
    icon: DollarSign,
    name: "sale management",
    type: "sub",
    active: false,
    children: [
      { path: "/sales/billgenerate", title: "Bill Generate", type: "link" },
      { path: "/sales/orders", title: "Retail", type: "link" },
      { path: "/sales/wholesale", title: "Whole Sale", type: "link" },
      { path: "/sales/orders", title: "Export", type: "link" },
      // { path: "/sales/transactions", title: "Transactions", type: "link" },
    ],
  },
  // {
  //   title: "Coupons",
  //   icon: Tag,
  //   type: "sub",
  //   active: false,
  //   children: [
  //     { path: "/coupons/list-coupons", title: "List Coupons", type: "link" },
  //     {
  //       path: "/coupons/create-coupons",
  //       title: "Create Coupons",
  //       type: "link",
  //     },
  //   ],
  // },
  // {
  //   title: "Pages",
  //   icon: Clipboard,
  //   type: "sub",
  //   active: false,
  //   children: [
  //     { path: "/pages/list-page", title: "List Page", type: "link" },
  //     { path: "/pages/create-page", title: "Create Page", type: "link" },
  //   ],
  // },
  // {
  //   title: "Media",
  //   path: "/media",
  //   icon: Camera,
  //   type: "link",
  //   active: false,
  // },
  // {
  //   title: "Menus",
  //   icon: AlignLeft,
  //   type: "sub",
  //   active: false,
  //   children: [
  //     { path: "/menus/list-menu", title: "List Menu", type: "link" },
  //     { path: "/menus/create-menu", title: "Create Menu", type: "link" },
  //   ],
  // },
  {
    id: 10004,
    title: "Users",
    privilege: true,
    icon: UserPlus,
    name: "user management",
    type: "sub",
    active: false,
    children: [
      {
        title: "Customers",
        type: "sub",
        children: [
          { path: "/users/retail", title: "Retail", type: "link" },
          { path: "/users/wholesale", title: "Wholesale", type: "link" },
        ],
      },
      { path: "/users/create-user", title: "Create Admin", type: "link" },
      {
        path: "/users/createcustomer",
        title: "Create customer",
        type: "link",
      },
    ],
  },
  // {
  //   title: "Vendors",
  //   icon: Users,
  //   type: "sub",
  //   active: false,
  //   children: [
  //     { path: "/vendors/list_vendors", title: "Vendor List", type: "link" },
  //     { path: "/vendors/create-vendors", title: "Create Vendor", type: "link" },
  //   ],
  // },
  // {
  //   id:10005,
  //   title: "Location",
  //   icon: Chrome,
  //   name:"location management",
  //   type: "link",
  //   path:"/localization/transactions",
  //   privilege:true
  // },
  {
    id: 10006,
    title: "Reports",
    path: "/reports/report",
    name: "report management",
    icon: BarChart,
    type: "link",
    active: false,
    privilege: true,
  },
  // {
  //   id: 10008,
  //   title: "Invoice",
  //   path: "/invoice",
  //   icon: Archive,
  //   name: "invoice management",
  //   type: "link",
  //   privilege: true,
  //   active: false,
  // },
  {
    id: 10007,
    title: "Settings",
    name: "setting management",
    icon: Settings,
    type: "sub",
    active: false,
    privilege: true,
    children: [{ path: "/settings/profile", title: "Profile", type: "link" }],
  },

  // {
  //   title: "Login",
  //   path: "/auth/login",
  //   icon: LogIn,
  //   type: "link",
  //   active: false,
  // },
];
