// export const rootUrl = "http://localhost:4000";
export const rootUrl = "https://api.farmtake.com";
export const getBannerUrl = "/api/banner/getbannerwithoutCE";
export const postBannerUrl = "/api/banner";
export const deletebannerUrl = "/api/banner/delete";
export const getCategoryUrl = "/api/category";
export const postCategoryUrl = "/api/category";
export const deleteCategoryUrl = "/api/category/delete";
export const getSubCatetgoryUrl = "/api/subcategory";
export const postSubCatetgoryUrl = "/api/subcategory";
export const deleteSubCatetgoryUrl = "/api/subcategory/delete";
export const getSubCategoryByIdUrl = "/api/subcategory/getsubcategorybyid";
export const getAllUnitsUrl = "/api/unit";
export const postProductUrl = "/api/product";
export const deleteLocationUrl = "/api/location/delete";
export const deleteproductUrl = "/api/product/delete";
export const updateProducturl = "/api/product/update";
export const addLocationUrl = "/api/location/addlocation";
export const addAdminUrl = "/api/admin/add";
export const getAdminUrl = "/api/admin/user";
export const deleteAdminUrl = "/api/admin/delete";
export const getDefaultUrl = "/api/admin/defaultmenu";
export const loginAdmin = "/api/auth/adminlogin";
export const UpdateProfileUrl = "/api/admin/update";
export const getAllOrders = "/api/checkout/getallorder";
export const GetInvoiceUrl = "/api/invoice/get/";
export const CreateCustomerUrl = "/api/auth/client/create";
export const CreateWholeSaleUrl = "/api/customer/create";
export const ProductInventoryUrl = "/api/product/inventory";
export const UpdateProductStockUrl = "/api/product/updatestock";
export const getStateUrl = "/api/location/state/";
export const getCityUrl = "/api/location/city/";
export const getRetaliCustomerUrl = "/api/customer/retail";
export const getWholeSaleCustomerUrl="/api/customer/wholesale"
export const getAllproductUrl="/api/product/getallproduct"
export const wholeSaleOrderUrl="/api/wholesale/order"
export const updatebannerurl="/api/banner/update"
export const updateOrderStatusUrl="/api/checkout/updateorderstatus";
export const updateRetailUserUrl="/api/customer/retail/update";
export const getNotificationUrl="/api/notification"
export const updateNotifcationUrl="/api/notification/updatestatus";
export const GetAllUsers = "/api/admin/alluser";